version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432-5432'