server:
  port: 5050
jwt:
  token:
    expired: 3600000
    secret: jwtappdemo
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: cee1b924dbe9e15c66cf8ecf4eef7cd470c9086c50ce52a6b52bc4862867366c
    url: jdbc:postgresql://ec2-52-205-171-232.compute-1.amazonaws.com/d8h1e91m2v3j1k
    username: tlyfalzfuhyhcg
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password: msodgmtkanubxqqr
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: twitter.clone.application@gmail.com
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          #          accessTokenUri: https://www.googleapis.com/oauth2/v4/token
          #          clientAuthenticationScheme: form
          google:
            client-id: 43110405413-n05stkskoha4lm0eam1qt1hiqvv7uio2.apps.googleusercontent.com
            client-secret: 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
          #          preferTokenInfo: true
          scope:
            - email
            - profile
#          userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#          userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo